AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-oidc-custom-authorizer

  TrueMark AWS API Gateway Custom Authorizer that authorizes API requests against an OIDC provider.

Globals:
  Function:
    Timeout: 5

Resources:
  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: authorizer/
      Handler: authorizer
      Runtime: provided.al2
      # Architectures:
      #   - arm64
      Tracing: Active
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          AUTHORITY: "AUTH" # Lambda will request <AUTHORITY>/.well-known/openid-configuration to find the JWKS URI, etc.
          AUDIENCE: "AUD" # Name of the OIDC audience name for the protected resource
          LOG_LEVEL: "Trace" # ("Trace" | "Debug" | "Info" | "Warn" | "Error" | "Fatal")
    Metadata:
      BuildMethod: makefile

Outputs:
  AuthorizerFunction:
    Description: "TrueMark AWS API Gateway Custom Authorizer"
    Value: !GetAtt AuthorizerFunction.Arn
  AuthorizerFunctionIamRole:
    Description: "Implicit IAM Role created for Authorizer function"
    Value: !GetAtt AuthorizerFunctionRole.Arn
