name: beta

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        id: build
        run: |
          export AM_CLI_TELEMETRY=0
          make
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: |
            .aws-sam/build/AuthorizerFunction/authorizer
          retention-days: 5
